# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Prepare Analysis Configuration task
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'tmchugh777'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.sources=src
      sonar.projectKey=tmchugh777_pipelines-java

#- task: Maven@4
  #inputs:
    #mavenPomFile: 'pom.xml'
    #publishJUnitResults: true
    #testResultsFiles: '**/surefire-reports/TEST-*.xml'
    #javaHomeOption: 'JDKVersion'
    #mavenVersionOption: 'Default'
    #mavenAuthenticateFeed: false
    #effectivePomSkip: false
    #sonarQubeRunAnalysis: false
    #sqMavenPluginVersionChoice: 'latest'

#Build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    sqMavenPluginVersionChoice: 'latest'

#Run sonar scan
- task: SonarCloudAnalyze@1

#Publish results
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

#- task: ServiceNow-DevOps-Build-Sonar-Registration@1
  #inputs:
    #connectedServiceName: 'DevOps Connection'
    #sonarProjectKey: 'tmchugh777_pipelines-java'
    #sonarInstanceUrl: 'https://sonarcloud.io/'